spring.application.name=SpringLabb
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false
spring.web.resources.chain.cache=false
spring.devtools.livereload.enabled=true
spring.docker.compose.lifecycle-management=start_only
spring.datasource.url=jdbc:postgresql://localhost:5432/SpringLabb
spring.datasource.username=user
spring.datasource.password=myPass
